services:
  sqlite:
    container_name: mybackend_sqlite
    image: nouchka/sqlite3:latest
    volumes:
      - ./db.sqlite:/var/lib/sqlite/data/db.sqlite
    ports:
      - "5432:5432"

  node:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - '3000:3000'  

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
      - '1025:1025'

  redis:
    image: redis:latest
    container_name: mybackend_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  postgres-data: {}
  maildir: {}
  redis-data: {}